server:
  port: 6001

spring:
  application:
    name: module1

  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: localhost
    port: 6379
    database: 1

mybatis:
  type-aliases-package: com.example.module1.model.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    #开启下划线转驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.module1.dao: debug

